# Copyright (C) 2015 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/trelte-common/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/samsung/trelte-common

# mcRegistry
PRODUCT_COPY_FILES += \
	vendor/samsung/trelte-common/proprietary/vendor/app/FFFFFFFF000000000000000000000001.drbin:$(TARGET_COPY_OUT_VENDOR)/app/FFFFFFFF000000000000000000000001.drbin \
	vendor/samsung/trelte-common/proprietary/vendor/app/mcRegistry/00060308060501020000000000000000.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/00060308060501020000000000000000.tlbin \
	vendor/samsung/trelte-common/proprietary/vendor/app/mcRegistry/02010000080300030000000000000000.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/02010000080300030000000000000000.tlbin \
	vendor/samsung/trelte-common/proprietary/vendor/app/mcRegistry/07010000000000000000000000000000.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/07010000000000000000000000000000.tlbin \
	vendor/samsung/trelte-common/proprietary/vendor/app/mcRegistry/07060000000000000000000000000000.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/07060000000000000000000000000000.tlbin \
	vendor/samsung/trelte-common/proprietary/vendor/app/mcRegistry/ffffffff00000000000000000000000a.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/ffffffff00000000000000000000000a.tlbin \
	vendor/samsung/trelte-common/proprietary/vendor/app/mcRegistry/ffffffff00000000000000000000000b.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/ffffffff00000000000000000000000b.tlbin \
	vendor/samsung/trelte-common/proprietary/vendor/app/mcRegistry/ffffffff00000000000000000000000c.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/ffffffff00000000000000000000000c.tlbin \
	vendor/samsung/trelte-common/proprietary/vendor/app/mcRegistry/ffffffff00000000000000000000000d.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/ffffffff00000000000000000000000d.tlbin \
	vendor/samsung/trelte-common/proprietary/vendor/app/mcRegistry/ffffffff00000000000000000000000e.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/ffffffff00000000000000000000000e.tlbin \
	vendor/samsung/trelte-common/proprietary/vendor/app/mcRegistry/ffffffff00000000000000000000000f.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/ffffffff00000000000000000000000f.tlbin \
	vendor/samsung/trelte-common/proprietary/vendor/app/mcRegistry/ffffffff00000000000000000000003e.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/ffffffff00000000000000000000003e.tlbin \
	vendor/samsung/trelte-common/proprietary/vendor/app/mcRegistry/ffffffff000000000000000000000004.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/ffffffff000000000000000000000004.tlbin \
	vendor/samsung/trelte-common/proprietary/vendor/app/mcRegistry/ffffffff000000000000000000000005.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/ffffffff000000000000000000000005.tlbin \
	vendor/samsung/trelte-common/proprietary/vendor/app/mcRegistry/ffffffff000000000000000000000011.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/ffffffff000000000000000000000011.tlbin \
	vendor/samsung/trelte-common/proprietary/vendor/app/mcRegistry/ffffffff000000000000000000000012.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/ffffffff000000000000000000000012.tlbin \
	vendor/samsung/trelte-common/proprietary/vendor/app/mcRegistry/ffffffff000000000000000000000013.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/ffffffff000000000000000000000013.tlbin \
	vendor/samsung/trelte-common/proprietary/vendor/app/mcRegistry/ffffffff000000000000000000000014.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/ffffffff000000000000000000000014.tlbin \
	vendor/samsung/trelte-common/proprietary/vendor/app/mcRegistry/ffffffff000000000000000000000016.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/ffffffff000000000000000000000016.tlbin \
	vendor/samsung/trelte-common/proprietary/vendor/app/mcRegistry/ffffffff000000000000000000000017.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/ffffffff000000000000000000000017.tlbin \
	vendor/samsung/trelte-common/proprietary/vendor/app/mcRegistry/ffffffff000000000000000000000018.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/ffffffff000000000000000000000018.tlbin \
	vendor/samsung/trelte-common/proprietary/vendor/app/mcRegistry/ffffffff000000000000000000000019.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/ffffffff000000000000000000000019.tlbin \
	vendor/samsung/trelte-common/proprietary/vendor/app/mcRegistry/ffffffff000000000000000000000041.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/ffffffff000000000000000000000041.tlbin \
	vendor/samsung/trelte-common/proprietary/vendor/app/mcRegistry/ffffffffd0000000000000000000000a.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/ffffffffd0000000000000000000000a.tlbin \
	vendor/samsung/trelte-common/proprietary/vendor/app/mcRegistry/ffffffffd0000000000000000000000e.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/ffffffffd0000000000000000000000e.tlbin \
	vendor/samsung/trelte-common/proprietary/vendor/app/mcRegistry/ffffffffd00000000000000000000004.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/ffffffffd00000000000000000000004.tlbin \
	vendor/samsung/trelte-common/proprietary/vendor/app/mcRegistry/ffffffffd00000000000000000000014.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/ffffffffd00000000000000000000014.tlbin \
	vendor/samsung/trelte-common/proprietary/vendor/app/mcRegistry/ffffffffd00000000000000000000016.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/ffffffffd00000000000000000000016.tlbin \
	vendor/samsung/trelte-common/proprietary/vendor/app/mcRegistry/fffffffff0000000000000000000001e.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/fffffffff0000000000000000000001e.tlbin

# Audio Blobs
#PRODUCT_COPY_FILES += \
#	vendor/samsung/trelte-common/proprietary/vendor/lib/hw/audio.primary.universal5433.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/audio.primary.universal5433.so \
#	vendor/samsung/trelte-common/proprietary/vendor/lib/lib_DNSe_NRSS_ver226.so:$(TARGET_COPY_OUT_VENDOR)/lib/lib_DNSe_NRSS_ver226.so \
#	vendor/samsung/trelte-common/proprietary/vendor/lib/lib_Samsung_AudioZoom_v102.so:$(TARGET_COPY_OUT_VENDOR)/lib/lib_Samsung_AudioZoom_v102.so \
#	vendor/samsung/trelte-common/proprietary/vendor/lib/lib_Samsung_Resampler.so:$(TARGET_COPY_OUT_VENDOR)/lib/lib_Samsung_Resampler.so \
#	vendor/samsung/trelte-common/proprietary/vendor/lib/lib_SamsungRec_V04013.so:$(TARGET_COPY_OUT_VENDOR)/lib/lib_SamsungRec_V04013.so \
# 	vendor/samsung/trelte-common/proprietary/vendor/lib/lib_SoundAlive_SRC192_ver205.so:$(TARGET_COPY_OUT_VENDOR)/lib/lib_SoundAlive_SRC192_ver205.so \
#	vendor/samsung/trelte-common/proprietary/vendor/lib/lib_soundaliveresampler.so:$(TARGET_COPY_OUT_VENDOR)/lib/lib_soundaliveresampler.so \
#	vendor/samsung/trelte-common/proprietary/vendor/lib/lib_SoundBooster_ver610.so:$(TARGET_COPY_OUT_VENDOR)/lib/lib_SoundBooster_ver610.so \
#	vendor/samsung/trelte-common/proprietary/vendor/lib/libaudio-ril.so:$(TARGET_COPY_OUT_VENDOR)/lib/libaudio-ril.so \
#	vendor/samsung/trelte-common/proprietary/vendor/lib/libsamsungRecord.so:$(TARGET_COPY_OUT_VENDOR)/lib/libsamsungRecord.so \
#	vendor/samsung/trelte-common/proprietary/vendor/lib/libsamsungRecord_ns.so:$(TARGET_COPY_OUT_VENDOR)/lib/libsamsungRecord_ns.so \
#	vendor/samsung/trelte-common/proprietary/vendor/lib/libsamsungRecord_zoom.so:$(TARGET_COPY_OUT_VENDOR)/lib/libsamsungRecord_zoom.so \
#	vendor/samsung/trelte-common/proprietary/vendor/lib/libsamsungSoundbooster_ext.so:$(TARGET_COPY_OUT_VENDOR)/lib/libsamsungSoundbooster_ext.so \
#	vendor/samsung/trelte-common/proprietary/vendor/lib/libtinyalsa.so:$(TARGET_COPY_OUT_VENDOR)/lib/libtinyalsa-M.so \
#	vendor/samsung/trelte-common/proprietary/vendor/lib/libtinycompress.so:$(TARGET_COPY_OUT_VENDOR)/lib/libtinycompress-M.so \
#	vendor/samsung/trelte-common/proprietary/vendor/lib/libunshorten.so:$(TARGET_COPY_OUT_VENDOR)/lib/libunshorten.so \
#	vendor/samsung/trelte-common/proprietary/usr/share/alsa/alsa.conf:$(TARGET_COPY_OUT_VENDOR)/usr/share/alsa/alsa.conf

# Other Blobs
PRODUCT_COPY_FILES += \
    vendor/samsung/trelte-common/proprietary/bin/gps.cer:$(TARGET_COPY_OUT_SYSTEM)/bin/gps.cer \
    vendor/samsung/trelte-common/proprietary/etc/firmware/florida-dsp1-edac.bin:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/florida-dsp1-edac.bin \
    vendor/samsung/trelte-common/proprietary/etc/firmware/florida-dsp1-edac.wmfw:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/florida-dsp1-edac.wmfw \
    vendor/samsung/trelte-common/proprietary/etc/firmware/florida-dsp2-tx-fb-meeting.bin:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/florida-dsp2-tx-fb-meeting.bin \
    vendor/samsung/trelte-common/proprietary/etc/firmware/florida-dsp2-tx-fb-meeting.wmfw:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/florida-dsp2-tx-fb-meeting.wmfw \
    vendor/samsung/trelte-common/proprietary/etc/firmware/florida-dsp2-tx-nb.wmfw:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/florida-dsp2-tx-nb.wmfw \
    vendor/samsung/trelte-common/proprietary/etc/firmware/florida-dsp2-tx-swb.wmfw:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/florida-dsp2-tx-swb.wmfw \
    vendor/samsung/trelte-common/proprietary/etc/firmware/florida-dsp2-tx-wb.wmfw:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/florida-dsp2-tx-wb.wmfw \
    vendor/samsung/trelte-common/proprietary/etc/firmware/florida-dsp3-ez2-control.wmfw:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/florida-dsp3-ez2-control.wmfw \
    vendor/samsung/trelte-common/proprietary/etc/firmware/florida-dsp3-lpsd-control.bin:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/florida-dsp3-lpsd-control.bin \
    vendor/samsung/trelte-common/proprietary/etc/firmware/florida-dsp3-tx-nb.bin:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/florida-dsp3-tx-nb.bin \
    vendor/samsung/trelte-common/proprietary/etc/firmware/florida-dsp3-tx-nb.wmfw:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/florida-dsp3-tx-nb.wmfw \
    vendor/samsung/trelte-common/proprietary/etc/firmware/florida-dsp3-tx-swb-conversation.bin:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/florida-dsp3-tx-swb-conversation.bin \
    vendor/samsung/trelte-common/proprietary/etc/firmware/florida-dsp3-tx-swb-interview.bin:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/florida-dsp3-tx-swb-interview.bin \
    vendor/samsung/trelte-common/proprietary/etc/firmware/florida-dsp3-tx-swb.wmfw:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/florida-dsp3-tx-swb.wmfw \
    vendor/samsung/trelte-common/proprietary/etc/firmware/florida-dsp3-tx-wb-meeting.bin:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/florida-dsp3-tx-wb-meeting.bin \
    vendor/samsung/trelte-common/proprietary/etc/firmware/florida-dsp3-tx-wb-meeting.wmfw:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/florida-dsp3-tx-wb-meeting.wmfw \
    vendor/samsung/trelte-common/proprietary/etc/firmware/florida-dsp3-tx-wb.bin:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/florida-dsp3-tx-wb.bin \
    vendor/samsung/trelte-common/proprietary/etc/firmware/florida-dsp3-tx-wb.wmfw:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/florida-dsp3-tx-wb.wmfw \
    vendor/samsung/trelte-common/proprietary/etc/firmware/florida-dsp4-dsm.wmfw:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/florida-dsp4-dsm.wmfw \
    vendor/samsung/trelte-common/proprietary/etc/firmware/florida-dsp4-rx-anc-nb.bin:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/florida-dsp4-rx-anc-nb.bin \
    vendor/samsung/trelte-common/proprietary/etc/firmware/florida-dsp4-rx-anc-nb.wmfw:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/florida-dsp4-rx-anc-nb.wmfw \
    vendor/samsung/trelte-common/proprietary/etc/firmware/florida-dsp4-rx-anc-wb.bin:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/florida-dsp4-rx-anc-wb.bin \
    vendor/samsung/trelte-common/proprietary/etc/firmware/florida-dsp4-rx-anc-wb.wmfw:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/florida-dsp4-rx-anc-wb.wmfw \
    vendor/samsung/trelte-common/proprietary/lib/libaudioroute.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libaudioroute.so \
    vendor/samsung/trelte-common/proprietary/vendor/bin/argosd:$(TARGET_COPY_OUT_VENDOR)/bin/argosd \
    vendor/samsung/trelte-common/proprietary/vendor/bin/gpsd:$(TARGET_COPY_OUT_VENDOR)/bin/gpsd \
    vendor/samsung/trelte-common/proprietary/vendor/bin/lhd:$(TARGET_COPY_OUT_VENDOR)/bin/lhd \
    vendor/samsung/trelte-common/proprietary/vendor/bin/sensorhubservice:$(TARGET_COPY_OUT_VENDOR)/bin/sensorhubservice \
    vendor/samsung/trelte-common/proprietary/vendor/bin/vcsFPService:$(TARGET_COPY_OUT_VENDOR)/bin/vcsFPService \
    vendor/samsung/trelte-common/proprietary/vendor/etc/wifi/bcmdhd_apsta.bin:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/bcmdhd_apsta.bin \
    vendor/samsung/trelte-common/proprietary/vendor/etc/wifi/bcmdhd_ibss.bin:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/bcmdhd_ibss.bin \
    vendor/samsung/trelte-common/proprietary/vendor/etc/wifi/bcmdhd_mfg.bin:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/bcmdhd_mfg.bin \
    vendor/samsung/trelte-common/proprietary/vendor/etc/wifi/bcmdhd_sta.bin:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/bcmdhd_sta.bin \
    vendor/samsung/trelte-common/proprietary/vendor/etc/wifi/cred.conf:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/cred.conf \
    vendor/samsung/trelte-common/proprietary/vendor/etc/wifi/nvram_mfg.txt:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/nvram_mfg.txt \
    vendor/samsung/trelte-common/proprietary/vendor/etc/wifi/nvram_mfg.txt_a0:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/nvram_mfg.txt_a0 \
    vendor/samsung/trelte-common/proprietary/vendor/etc/wifi/nvram_mfg.txt_murata:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/nvram_mfg.txt_murata \
    vendor/samsung/trelte-common/proprietary/vendor/etc/wifi/nvram_net.txt:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/nvram_net.txt \
    vendor/samsung/trelte-common/proprietary/vendor/etc/wifi/nvram_net.txt_a0:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/nvram_net.txt_a0 \
    vendor/samsung/trelte-common/proprietary/vendor/etc/wifi/nvram_net.txt_murata:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/nvram_net.txt_murata \
    vendor/samsung/trelte-common/proprietary/vendor/etc/lhd.conf:$(TARGET_COPY_OUT_VENDOR)/etc/lhd.conf \
    vendor/samsung/trelte-common/proprietary/vendor/firmware/bcm4358A0_V0033.0000.hcd:$(TARGET_COPY_OUT_VENDOR)/firmware/bcm4358A0_V0033.0000.hcd \
    vendor/samsung/trelte-common/proprietary/vendor/firmware/BCM4358A1_V0054.0094_wisol.hcd:$(TARGET_COPY_OUT_VENDOR)/firmware/BCM4358A1_V0054.0094_wisol.hcd \
    vendor/samsung/trelte-common/proprietary/vendor/firmware/BCM4358A1_V0054.0094.hcd:$(TARGET_COPY_OUT_VENDOR)/firmware/BCM4358A1_V0054.0094.hcd \
    vendor/samsung/trelte-common/proprietary/vendor/firmware/hevc_fw.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/hevc_fw.bin \
    vendor/samsung/trelte-common/proprietary/vendor/firmware/mfc_fw.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/mfc_fw.bin \
    vendor/samsung/trelte-common/proprietary/vendor/firmware/fimc_is_fw2_imx240.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/fimc_is_fw2_imx240.bin \
    vendor/samsung/trelte-common/proprietary/vendor/firmware/fimc_is_ois_63A.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/fimc_is_ois_63A.bin \
    vendor/samsung/trelte-common/proprietary/vendor/firmware/fimc_is_ois_63B.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/fimc_is_ois_63B.bin \
    vendor/samsung/trelte-common/proprietary/vendor/firmware/companion_default_coef.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/companion_default_coef.bin \
    vendor/samsung/trelte-common/proprietary/vendor/firmware/companion_default_lsc.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/companion_default_lsc.bin \
    vendor/samsung/trelte-common/proprietary/vendor/firmware/companion_fw_imx240_evt1.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/companion_fw_imx240_evt1.bin \
    vendor/samsung/trelte-common/proprietary/vendor/firmware/companion_imx240_master_setfile.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/companion_imx240_master_setfile.bin \
    vendor/samsung/trelte-common/proprietary/vendor/firmware/companion_imx240_mode_setfile.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/companion_imx240_mode_setfile.bin \
    vendor/samsung/trelte-common/proprietary/vendor/firmware/seiren_fw_dram.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/seiren_fw_dram.bin \
    vendor/samsung/trelte-common/proprietary/vendor/firmware/seiren_fw_sram.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/seiren_fw_sram.bin \
    vendor/samsung/trelte-common/proprietary/vendor/firmware/setfile_6d1.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/setfile_6d1.bin \
    vendor/samsung/trelte-common/proprietary/vendor/firmware/setfile_imx240.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/setfile_imx240.bin \
    vendor/samsung/trelte-common/proprietary/vendor/lib/egl/libGLES_mali.so:$(TARGET_COPY_OUT_VENDOR)/lib/egl/libGLES_mali.so \
    vendor/samsung/trelte-common/proprietary/vendor/lib/hw/camera.vendor.universal5433.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/camera.vendor.universal5433.so \
    vendor/samsung/trelte-common/proprietary/vendor/lib/hw/consumerir.exynos5.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/consumerir.exynos5.so \
    vendor/samsung/trelte-common/proprietary/vendor/lib/hw/flp.default.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/flp.default.so \
    vendor/samsung/trelte-common/proprietary/vendor/lib/hw/gps.universal5433.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/gps.universal5433.so \
    vendor/samsung/trelte-common/proprietary/vendor/lib/hw/sensorhubs.universal5433.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/sensorhubs.universal5433.so \
    vendor/samsung/trelte-common/proprietary/vendor/lib/hw/sensors.vendor.universal5433.so:$(TARGET_COPY_OUT_VENDOR)/lib/sensors.vendor.universal5433.so \
    vendor/samsung/trelte-common/proprietary/vendor/lib/mediadrm/libwvdrmengine.so:$(TARGET_COPY_OUT_VENDOR)/lib/mediadrm/libwvdrmengine.so \
    vendor/samsung/trelte-common/proprietary/vendor/lib/soundfx/liblvverx.so:$(TARGET_COPY_OUT_VENDOR)/lib/soundfx/liblvverx.so \
    vendor/samsung/trelte-common/proprietary/vendor/lib/soundfx/liblvvetx.so:$(TARGET_COPY_OUT_VENDOR)/lib/soundfx/liblvvetx.so \
    vendor/samsung/trelte-common/proprietary/vendor/lib/libexynoscamera.so:$(TARGET_COPY_OUT_VENDOR)/lib/libexynoscamera.so \
    vendor/samsung/trelte-common/proprietary/vendor/lib/libfloatingfeature.so:$(TARGET_COPY_OUT_VENDOR)/lib/libfloatingfeature.so \
    vendor/samsung/trelte-common/proprietary/vendor/lib/libfpasmtztransport.so:$(TARGET_COPY_OUT_VENDOR)/lib/libfpasmtztransport.so \
    vendor/samsung/trelte-common/proprietary/vendor/lib/libgnustl_shared.so:$(TARGET_COPY_OUT_VENDOR)/lib/libgnustl_shared.so \
    vendor/samsung/trelte-common/proprietary/vendor/lib/libhwjpeg.so:$(TARGET_COPY_OUT_VENDOR)/lib/libhwjpeg.so \
    vendor/samsung/trelte-common/proprietary/vendor/lib/libprotobuf-cpp-fooo.so:$(TARGET_COPY_OUT_VENDOR)/lib/libprotobuf-cpp-fooo.so \
    vendor/samsung/trelte-common/proprietary/vendor/lib/libsecnativefeature.so:$(TARGET_COPY_OUT_VENDOR)/lib/libsecnativefeature.so \
    vendor/samsung/trelte-common/proprietary/vendor/lib/libsensorhub.so:$(TARGET_COPY_OUT_VENDOR)/lib/libsensorhub.so \
    vendor/samsung/trelte-common/proprietary/vendor/lib/libsensorhubservice.so:$(TARGET_COPY_OUT_VENDOR)/lib/libsensorhubservice.so \
    vendor/samsung/trelte-common/proprietary/vendor/lib/libvalAuth.so:$(TARGET_COPY_OUT_VENDOR)/lib/libvalAuth.so \
    vendor/samsung/trelte-common/proprietary/vendor/lib/libvcsfp.so:$(TARGET_COPY_OUT_VENDOR)/lib/libvcsfp.so \
    vendor/samsung/trelte-common/proprietary/vendor/lib/libvdis.so:$(TARGET_COPY_OUT_VENDOR)/lib/libvdis.so \
    vendor/samsung/trelte-common/proprietary/vendor/lib/libvfmClient.so:$(TARGET_COPY_OUT_VENDOR)/lib/libvfmClient.so \
    vendor/samsung/trelte-common/proprietary/vendor/lib/libvfmtztransport.so:$(TARGET_COPY_OUT_VENDOR)/lib/libvfmtztransport.so \
    vendor/samsung/trelte-common/proprietary/vendor/lib/libwrappergps.so:$(TARGET_COPY_OUT_VENDOR)/lib/libwrappergps.so
